[tool.poetry]
name = "arrange-it"
version = "0.1.0"
description = ""
authors = ["Maxim Dunaev"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.85.0"
uvicorn = "^0.18.3"
pytest = "^7.1.3"
asyncpg = "^0.26.0"
asyncio = "^3.4.3"
pytest-asyncio = "^0.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
