repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ --safe ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        entry: bash -c 'poetry install && mypy app'
        verbose: true
        additional_dependencies: [
          'pydantic',
        ]
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        entry: bash -c 'pylint app || pylint-exit -efail $?'
        verbose: true
        additional_dependencies: [
          'pylint_pydantic',
          'pylint-exit',
        ]

